### ISSUE TITLE
[wish] add a short description and the link to the website

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#10]
In the [main GitHub page](https://github.com/MediaArea/RAWcooked) add

- a short description
- the link to the [MediaArea](https://mediaarea.net/RAWcooked)’s dedicated homepage

instead of `Not yet ready for production use, for tests only`. Sorry, I cannot open myself a PR for this.

**Comment by JeromeMartinez** [comment]
I added the short description + the link, but I prefer to keep the warning message until we have a stable release, in order to avoid that people yell because I would have destroy their files (I don't expect to do that, but as it is an alpha release...).
