### ISSUE TITLE
FFmpeg warnings when encoding/decoding

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/RAWcooked#100]
When encoding DPX (gbrp10le), I get warnings when encoding/decoding with rawcooked.

**Encoding:**
> [matroska @ 0x1391ee0] Codec for stream 1 does not use global headers but container format requires global headers
> [matroska @ 0x1391ee0] Codec for stream 2 does not use global headers but container format requires global headers

**Decoding/Playback:**
> The tags at index 2 refer to a non-existent track 2.=    0B f=0/0   
> The tags at index 3 refer to a non-existent track 3.
> The tags at index 5 refer to a non-existent track 2.
> The tags at index 6 refer to a non-existent track 3.
> [matroska,webm @ 0x7f702c000940] Could not find codec parameters for stream 1 (Attachment: none): unknown codec
> Consider increasing the value for the 'analyzeduration' and 'probesize' options
> [matroska,webm @ 0x7f702c000940] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
> Consider increasing the value for the 'analyzeduration' and 'probesize' options

**Stream layout:**
```
Input #0, matroska,webm, from 'test2.mkv':
  Metadata:
    ENCODER         : Lavf56.40.101
  Duration: 00:00:02.08, start: 0.000000, bitrate: 13027 kb/s
    Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), gbrp10le, 1920x1080, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      ENCODER         : Lavc56.60.100 ffv1
      DURATION        : 00:00:02.084000000
    Stream #0:1: Attachment: none
    Metadata:
      filename        : test2/md5sums.md5
      mimetype        : application/octet-stream
    Stream #0:2: Attachment: none
    Metadata:
      filename        : RAWcooked reversibility data
      mimetype        : application/octet-stream
   1.12 M-V:  0.003 fd=   2 aq=    0KB vq=  863KB sq=    0B f=0/0
```

**Comment by JeromeMartinez** [comment]
Please provide the result of `rawcooked test2 --display-command`

**Comment by pjotrek-b** [comment]
`ffmpeg -framerate 24 -start_number 000001 -i "test2/%06d.dpx" -c:a flac -c:v ffv1 -coder 1 -context 1 -f matroska -g 1 -level 3 -slicecrc 1 -slices 64 -attach "test2/md5sums.md5" -metadata:s:1 mimetype=application/octet-stream -metadata:s:1 "filename=test2/md5sums.md5" -attach "test2.rawcooked_reversibility_data" -metadata:s:2 mimetype=application/octet-stream -metadata:s:2 "filename=RAWcooked reversibility data" "test2.mkv"`

**Comment by pjotrek-b** [comment]
Yes, default ffmpeg libs from Ubuntu 16.04 repositories: 7:2.8.14-0ubuntu0.16.04.1

The files behave fine, and you don't have those warnings (with recent ffmpeg libs) - so shall I close this?

**Comment by retokromer** [comment]
If you update «normally» FFmpeg in Ubuntu, you should have `FFmpeg 4.0`… even in `Ubuntu 14.04.5 LTS`.

**Comment by retokromer** [comment]
P.S. – I guess, the maintaining of `FFmpeg 2.8.14` will be abandoned as soon as `FFmpeg 4.0.1` will be released.

**Comment by JeromeMartinez** [comment]
Third point is not away, is it acceptable for all?

**Comment by retokromer** [comment]
On my side, yes.

**Comment by pjotrek-b** [comment]
@retokromer: Regarding ffmpeg 4.0 "even in Ubuntu 14.04.5":

I've checked on my setup, as well as [the Ubuntu package info for ffmpeg](https://packages.ubuntu.com/xenial-updates/ffmpeg): v2.8.14 is the latest available from plain-vanilla repositories.

Am I missing something?
Do you have 3rd party repos added to your 14.04 setup?

**Comment by retokromer** [comment]
@pjotrek-b Sorry for being unclear! As «normally» I meant by compiling the code. However, I guess, it works also with Linuxbrew, but I have to check this on Monday.

**Comment by retokromer** [comment]
@pjotrek-b Me wrong! Josh tells me that the standard Linuxbrew installation is still `FFmpeg 3.3.4`, but he forced [`FFmpeg 4.0`](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/ffmpeg.rb) for us.

**Comment by JeromeMartinez** [comment]
As the 2 first points are from FFmpeg and "fixed" in later version of FFmpeg, and as the third point looks lie acceptable, closing the ticket, please open it again if there are new comments about it.
