### ISSUE TITLE
Wishlist: Progress indicator when decoding back to DPX

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/RAWcooked#101]
Reversing the MKV back to DPX sequences works properly, but there is no progress indicator whatsoever.

It would be nice to have some means of showing any progress (or to see that rawcooked is still alive).
Just an idea :smiley:

**Comment by retokromer** [comment]
+1

**Comment by pjotrek-b** [comment]
Wonderful! Wunderbar :smile: :+1:

For curious onlookers, here's a preview of what it now looks like:
`Time=00:00:02 (7%), 44 MiB/s, 0.36x realtime`

Thank @JeromeMartinez :cake:
