### ISSUE TITLE
Cannot encode larger RIFF than 6704894 bytes

### ISSUE THREAD

**Issue by lsde** [MediaArea/RAWcooked#128]
Hi,
what is the status of audio encoding, did anybody encode anything larger than the testing files?
Because I found out that RAWcooked cannot encode anything larger than 6704894 bytes, regardless of type ('0x1' or '0xfffe') or bit depth (16 or 24), sampling (44100 or 48000), ChannelMask (mono or 5.1) etc..

It always ends up on this boundary.
One example:

```
$ ffmpeg -f lavfi -i sine -c:a pcm_s16le -t 76.018333 bla.wav
..
$ ls -l bla.wav
-rw-rw-r--. 1 user user 6704894 Aug  3 19:02 bla.wav
$ rawcooked bla.wav
..
(works)
$ ls -l bla.wav.mkv
-rw-rw-r--. 1 user user 918246 Aug  3 19:03 bla.wav.mkv
```

```
$ ffmpeg -f lavfi -i sine -c:a pcm_s16le -t 76.018334 bla.wav
..
$ ls -l bla.wav
-rw-rw-r--. 1 user user 6704896 Aug  3 19:04 bla.wav
$ rawcooked bla.wav
bla.wav is not small, expected to be an attachment? Please contact info@mediaarea.net if you want support of such file.
```

**Comment by JeromeMartinez** [comment]
the algo for detecting unexpected directory structures incorrectly rejects this wav file and tries to consider it as attachment (and we currently reject big attachment exactly for finding such kind of issue), definitely a bug in the algo.
Note: can be reproduced on CentOS, but is fine on Windows, so platform specific.

**Comment by JeromeMartinez** [comment]
@lsde please test [latest snapshot](https://mediaarea.net/download/snapshots/binary/rawcooked/).

**Comment by retokromer** [comment]
> i will try to persuade my institution to consider a sponshorship

Indeed a good move, @lsde, thank you!
