### ISSUE TITLE
Losslessness check?

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/RAWcooked#140]
Hi,
I'm only starting to do some testing, so far, RAWCooked is very very slick :)

I was wondering if there is any kind of losslessness check involved in the DPX -> FFV1 process?
it does not appear to be the case. I think that some sort of PASS/FAIL test could increase trust in RAWCooked.

I am most likely going to write a python script that will use RAWCooked to encode, then it will perform a validation in the form of reconstructing the DPX sequence and checking if the whole file MD5s are the same.
I might also look into framemd5 validation, but it might not be needed if the goal of RAWCOoked is to have whole-file losslessness.

**Comment by JeromeMartinez** [comment]
> I was wondering if there is any kind of losslessness check involved in the DPX -> FFV1 process?

This is something I have in mind e.g. if the target directory already exists I run a check instead of decompressing, but not sure I will implement it before first public release.
In the meanwhile we added such test in our [test procedures](https://github.com/MediaArea/RAWcooked/tree/master/Project/GNU/CLI/test).

> I might also look into framemd5 validation

We also have such test, but I am thinking to remove it because the MD5 is actually more strict than framemd5.

**Comment by kieranjol** [comment]
Cool, I saw that there was some framehash code within RAWCooked, but would it be safe to say that this is not used currently?

I agree that MD5 is much easier than framemd5 in this regard, as the MD5 check will also leave out the need for checking if all metadata is correct and all that.

**Comment by JeromeMartinez** [comment]
> I saw that there was some framehash code within RAWCooked, but would it be safe to say that this is not used currently?

True. Planned at long term but not yet implemented. I prefer to implement it when I have my own encoder, else files would be parsed twice (with FFmpeg encoder & for MD5), slow, if there is not already a MD5 file (it could be used too...).

Note that this is slightly different that what I have in mind, there are 2 things here:
- "autotest" from MD5 signature (or MD5 file if it is already present)
- "full test" from original files

**Comment by kieranjol** [comment]
I'm thinking the same thing for my script..
For the `autotest` in rawcooked, perhaps the user could supply the checksum manifest (via a `-md5` option?) in the bagit/md5sum relative path style rather than rawcooked having to guess the location? Though I guess a sidecar md5 file to the input folder could be auto-detected, but the manifest location could be unpredicable depending on an archive's folder structure.

**Comment by JeromeMartinez** [comment]
auto-detection should be easy (.md5 or .md5sum file :) ), I'll implement a first version then we'll see if there is some customization to do.

**Comment by kieranjol** [comment]
This can be closed I think? Looks like it's been implemented.
