### ISSUE TITLE
Reversibility attachment data format

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/RAWcooked#143]
I was wondering what format the actual reversibility attachment is? I extracted it with mkvextract and looked at it in a hex editor, but aside from some RAWCooked version info at the start, I can't figure it out. I assumed that it was perhaps a compress (with what?) header of the first DPX file?

**Comment by JeromeMartinez** [comment]
I started to write the doc in [/Doc](https://github.com/MediaArea/RAWcooked/blob/master/Doc/File_Stucture.md) dir, but it definitely needs to be expanded e.g. the EBML values are missing.
On my ToDo-list.

**Comment by kieranjol** [comment]
This is cool, exactly what I wanted! That answers my question anyhow.
