### ISSUE TITLE
FFmpeg -report for FFV1 process?

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/RAWcooked#144]
I was wondering if it would be possible to add an option to RAWCooked that would invoke the `-report` option in FFmpeg? This would allow a logfile to be created for the transcode. This would be extremely useful for an archive to store in an archival package as evidence of the normalisation process.

**Comment by kieranjol** [comment]
Also, when the rawcooked encoder goes live, this option will either be redundant as ffmpeg will not be used, or else some other rawcooked logging could be stored, perhaps as a sidecar.log file in both instances?

**Comment by JeromeMartinez** [comment]
Checking [FFmpeg documentation](https://ffmpeg.org/ffmpeg.html), it looks like the report [can be generated also with `FFREPORT` environment variable](https://trac.ffmpeg.org/ticket/1823), so without changing RAWcooked.

I could authorize `-report` option (it does not change the encoding), but not sure that it is worth it.

for when I have my own encoder: I'll see what is easily doable without spending much time on it (would be on my spare time).

**Comment by kieranjol** [comment]
Hmm,I use the Ffreport environment variable when calling ffmpeg via
python,but I always use the -report option with it.ill see if I can call
rawcooked via python and use the Ffreport variable to pull out the log into
a file.

**Comment by kieranjol** [comment]
That worked!! Thank you so much, this is so cool
