### ISSUE TITLE
Running command from first .dpx file in directory

### ISSUE THREAD

**Issue by b00giehead** [MediaArea/RAWcooked#145]
I've been making initial tests of RawCooked and had a test scan directory containing DPX files and a single WAV.  Using an older version of RAWCooked I attempted a MKV conversion on the /Scan01/ folder and received the error:
"Untested WAV FormatTag ChannelMask, please contact info@mediaarea.net."

I managed to convert the directory by redirecting the rawcooked command to the first .dpx file in the /Scan01/ directory.  This MKV would not play in my Mac VLC player version 2.0.9, which I understand is too old a version now so I'll upgrade later today and test again. Upon re-expansion of the MKV I found that the WAV file was missing, and the resulting directory .01 GB smaller in size. The MKV was significantly smaller file size than the Scan 01 folder though, and a few random MD5 checksum tests of DPX files from original directory and MKV expanded directory were perfect matches.

**Comment by JeromeMartinez** [comment]
> I've been making initial tests of RawCooked 

thank you!

> "Untested WAV FormatTag ChannelMask, please contact info@mediaarea.net."

Is it fixed [with this version](https://mediaarea.net/download/snapshots/binary/rawcooked/20180901/)?

> Upon re-expansion of the MKV I found that the WAV file was missing,

Normal in that case that the WAV file is not used, as the DPX is explicitly requested.
I understand from your comment that you didn't expect that the WAV files (and any other sidecar file) are not compressed, this may be dangerous if the user expects that all is taken from the folder with this command, so I'll forbid the use of .dpx directly without explicit option indicating that this is wanted.

**Comment by kieranjol** [comment]
On a side note,Joanna I'm  doing some testing at the moment as well,and I
plan to write a blog on the tests too soon. I might drop you a line at some
point to share our findings?

**Comment by b00giehead** [comment]
Yep, sounds great Kieran. Please be patient with my 'newbie' status though.

**Comment by JeromeMartinez** [comment]
I need the first KB of the file, would you mind to share it?
`head -c 1000 FileName.wav > dump.wav` would create a file dump dump.wav from FileName.wav (name to be replaced by the right one) with 1000 bytes only, so no copyright issue IMO.

**Comment by b00giehead** [comment]
Okay, thanks that's a better option. dump.wav created i'll email you with it now.

**Comment by JeromeMartinez** [comment]
The WAV file contains a `channelMask` I filter (it is set to 0 = no mask instead of saying the channel position of the channel).
Note: I am very strict on the different configurations of the files because I want to test any element which could lead to a different behavior of FFmpeg e.g. channel reordering, this would break reversibility.

As decoding is fine with such config, I add them to the white list.

**Comment by b00giehead** [comment]
Will this be something that needs altering a point of capture of the WAV?

**Comment by JeromeMartinez** [comment]
> Will this be something that needs altering a point of capture of the WAV?

It is not important, especially for mono streams, it is just no explicit channel positioning.
[Channel Mask documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/channel-mask) is not explicit about the need of filling it with the right count of bits set to 1 (1 bit set for mono, 2 bits set for stereo...), and on our side it is not an issue for reversibility.

**Comment by JeromeMartinez** [comment]
> "Untested WAV FormatTag ChannelMask, please contact info@mediaarea.net."

This part should be fixed with [the latest snapshot](https://mediaarea.net/download/snapshots/binary/rawcooked/).

I keep this ticket open for the other issue (avoiding "WAV file was missing" question by adding an explicit option for parsing a file or sequence of files instead of a directory)

**Comment by JeromeMartinez** [comment]
> Upon re-expansion of the MKV I found that the WAV file was missing, 

Now parsing directly a DPX file is rejected by default, so it is more explicit that this is for parsing only the file and not the complete directory.
[Snapshots](https://mediaarea.net/download/snapshots/binary/) are updated.

I think that now all indicated issues are resolved.
