### ISSUE TITLE
set output directory for restoring FFv1 -> DPX

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/RAWcooked#148]
I can use `-o` for stipulating the ffv1 filename for the DPX-> FFV1 process, but is there a way to set the output directory for the FFV1 -> DPX process?

```
$ rawcooked '/tmp/04ac946a-5e37-4ef8-bdca-24474bc02965/df909af4-57b1-4234-b211-fd901e662d11.mkv'  -o '/home/kieranjol/Downloads' 
Unsupported output file extension. Please contact info@mediaarea.net if you want support of such output format.

```

**Comment by kieranjol** [comment]
Wow cool,thx!

**Comment by JeromeMartinez** [comment]
[Snapshots](https://mediaarea.net/download/snapshots/binary/rawcooked/) on the way (mini 20190912).
