### ISSUE TITLE
[wish] activate help

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#17]
The prompt says that there is a `rawcooked --help`, but is gives an error and not the [existing help](https://github.com/MediaArea/RAWcooked/blob/master/Source/CLI/Help.cpp):

<img width="890" alt="bildschirmfoto 2018-02-11 um 14 36 43" src="https://user-images.githubusercontent.com/3246607/36073957-27c3009c-0f39-11e8-968c-b764595e7181.png">

I made a [PR](https://github.com/MediaArea/RAWcooked/pull/16) for the man page.

**Comment by JeromeMartinez** [comment]
[Quick fix](https://github.com/MediaArea/RAWcooked/commit/97f12ba1075df2195b0172c14761758218d9734f), I'll expand the help part when I finish more features so integrated help and man page are in sync.

**Comment by retokromer** [comment]
Thank you! I was going to propose something very similar… after finishing to play with lenticular.

@JeromeMartinez : I can update the docs, if you wish so.

**Comment by pjotrek-b** [comment]
This is still an issue when using the short parameter "-h".
(Build rawcooked_18.01.20180217-1_amd64.xUbuntu_16.04.deb)

**Comment by retokromer** [comment]
I fixed it in the HEAD some days ago.

**Comment by retokromer** [comment]
See https://github.com/MediaArea/RAWcooked/pull/24

**Comment by retokromer** [comment]
@pjotrek-b It’s fixed now in the [daily](https://mediaarea.net/download/snapshots/binary/rawcooked/) releases as well.
