### ISSUE TITLE
crash in windows 7 

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/RAWcooked#188]
I am using Windows 7 and rawcooked 18.10.1 . I think I've never tried RAWcooked in Win7 before, only Win10, Ubuntu and OSX.
When I just type `rawcooked`, all seems well, but when I use `rawcooked -h`or supply a file as input, the program crashes and here is the error report that  Windows 7 provides:

````
C:\Users\hi>rawcooked
Usage: "rawcooked [options] DirectoryName [options]"
"rawcooked --help" for displaying more information
or "man rawcooked" for displaying the man page

C:\Users\hi>rawcooked -h
````
````
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RAWcooked.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5beb1aa0
  Fault Module Name:	RAWcooked.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5beb1aa0
  Exception Code:	c000001d
  Exception Offset:	000000000001262e
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	6153
  Additional Information 1:	8833
  Additional Information 2:	8833468c23e2f968ed35f4b3a75fc117
  Additional Information 3:	346d
  Additional Information 4:	346d185dc088fbc65b53fa650d291f84

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

````

**Comment by JeromeMartinez** [comment]
I tested on a clean Win7 v6.1.7601 (same as yours) a [RAWcooked development snapshot](https://mediaarea.net/download/snapshots/binary/rawcooked/20181208/RAWcooked_CLI_18.10.1.20181208_Windows_x64.zip) (due to another issue, the need of some DLLs not installed by default which is fixed in this version), and it is OK.

`c000001d` is usually for old CPU not supporting a specific instruction e.g. SSE or AVX, but IIRC we don't use advanced CPU instructionsm anyway what is the CPU used? it was also reported that this may be due to a corrupted exe, MD5 of 18.10.1 rawcooked.exe is 85DF14F234524AE89387A080B2AFD96A.

**Comment by kieranjol** [comment]
Merry christmas!
CPU is indeed old - Core2Quad Q8400. 

Checksum is the same - 85df14f234524ae89387a080b2afd96a

I was thinking that it could be a DLL thing alright... is there a way for me to be able to tell you which VS DLLs i have and have not? I installed the 2015 distributable as something like msvcp140.dll was missing when i first tried it.

i tried your snapshot - seems to be the same story:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RAWcooked.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5c0b2876
  Fault Module Name:	RAWcooked.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5c0b2876
  Exception Code:	c000001d
  Exception Offset:	0000000000016a9e
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	6153
  Additional Information 1:	8833
  Additional Information 2:	8833468c23e2f968ed35f4b3a75fc117
  Additional Information 3:	4716
  Additional Information 4:	4716afc5855ab9ee10e8e7157ee2a375

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

```

**Comment by kieranjol** [comment]
Awesome! I can't compile on windows but I'll have access to that computer for another 24 hours to test - if there's a snapshot?

**Comment by JeromeMartinez** [comment]
[snapshot with the fix](https://mediaarea.net/download/snapshots/binary/rawcooked/20181226-2/RAWcooked_CLI_18.10.1.20181226_Windows_x64.zip)
