### ISSUE TITLE
Very restrictive permissions when unpacking MKV

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/RAWcooked#204]
When unpacking the rawcooked Matroska file, I get "600" set as default permissions for the created files.

Is that on purpose?

For example:

**Input is:**
`-rwxrwxrwx 1 pb pb 17080320 Dec  6 13:17 pb_test1/reel_1/0092274.dpx`

**Output is:**
`-r-------- 1 pb pb 17080320 Mar 27 19:01 pb_test1.mkv.RAWcooked/pb_test1/reel_1/0092274.dpx`

This applies to *all* files created by RAWcooked.

Setup:
  * Xubuntu 16.04.6 (64bit)
  * RAWcooked 18.10.1.20190323

**Comment by JeromeMartinez** [comment]
> Is that on purpose?

Not really. Just that I was too restrictive in my new configuration when I switched to [open()](http://man7.org/linux/man-pages/man2/open.2.html).

Easy to change, but wondering now which rights should be by default. read, write for user/group/others?

**Comment by retokromer** [comment]
>but wondering now which rights should be by default

I would suggest 664.

**Comment by pjotrek-b** [comment]
I'd say "classic" would be:
  * 755 for folders
  * 644 for files

Or 775/664 to allow group write.

Is it possible to inherit from parent folder of target (default ".")?
That would be the most consistent.

**Comment by retokromer** [comment]
>I'd say "classic" would be:
>
>- 755 for folders
>- 644 for files

Indeed! Your example was a file…
