### ISSUE TITLE
could not open file/could not open attachment error

### ISSUE THREAD

**Issue by bturkus** [MediaArea/RAWcooked#222]
Hi All,

For some reason, I've been experiencing some sort of indeterminate RAWcooked "could not open file/could not open attachment" issue; here's the error messaging that I've been receiving:

```
MY-LPAMI-056430:~ benjaminturkus$ rawcooked --all /Volumes/NYPF257402/Film/data/PreservationMasters/10-bit_DPX/myd_380086_v01_pm_DPX 
Using default license.
Consider to support RAWcooked: https://MediaArea.net/RAWcooked

                                                            
Warning: non-conforming DPX Ditto key (x251).
At least 1 file is not conform to specifications.

Do you want to continue despite warnings ? [y/N] y
Track 1:
  myd_380086_v01_pm.wav
  WAV/PCM/96kHz/24bit/1ch/LE
  *** This input format flavor is not supported by the current license key. ***
Track 2:
  myd_380086_v01_pm_%07d.dpx
 (0000000 --> 0064056)
  DPX/Raw/RGB/10bit/FilledA/BE

One or more requested features are not supported with the current license key.
Please contact info@mediaarea.net for a quote or a temporary key.
Ignoring the license for the moment.

ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from '/Volumes/NYPF257402/Film/data/PreservationMasters/10-bit_DPX/myd_380086_v01_pm_DPX/myd_380086_v01_pm.wav':
  Metadata:
    title           : myd_380086_v01_pm_Audio 96.0KHz 24bit.wav
    copyright       : Lasergraphics Inc
    encoded_by      : Lasergraphics
    date            : 2018-05-23
    creation_time   : 17:20:37
    time_reference  : 0
    coding_history  : A=PCM,F=96000,W=24,M=mono,T=libsndfile-1.0.20 
                    : 
  Duration: 00:44:29.04, bitrate: 2304 kb/s
    Stream #0:0: Audio: pcm_s24le ([1][0][0][0] / 0x0001), 96000 Hz, mono, s32 (24 bit), 2304 kb/s
[image2 @ 0x7fc4d1052400] Could not open file : /Volumes/NYPF257402/Film/data/PreservationMasters/10-bit_DPX/myd_380086_v01_pm_DPX/myd_380086_v01_pm_0000000.dpx
[image2 @ 0x7fc4d1052400] Could not find codec parameters for stream 0 (Video: dpx, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #1, image2, from '/Volumes/NYPF257402/Film/data/PreservationMasters/10-bit_DPX/myd_380086_v01_pm_DPX/myd_380086_v01_pm_%07d.dpx':
  Duration: 00:44:29.04, start: 0.000000, bitrate: N/A
    Stream #1:0: Video: dpx, none, 24 tbr, 24 tbn, 24 tbc
Could not open attachment file /Volumes/NYPF257402/Film/data/PreservationMasters/10-bit_DPX/myd_380086_v01_pm_DPX.rawcooked_reversibility_data.
```
In terms of troubleshooting, I've tried cooking a small subset of the DPX files without problem, and I've rolled back to an older version of RAWcooked (RAWcooked_CLI_18.10.1.20190112_Mac.dmg) and again, I haven't experienced the same issue. I'm currently on RAWcooked 18.10.1, downloaded direct from Github.

Thanks for any help!

Ben

**Comment by JeromeMartinez** [comment]
The error message comes from FFmpeg, so it is very difficult to debug from RAWcooked point of view. Weird that the message is from FFmpeg and depends on the RAWcooked version.

Is it repeatable i.e. happens at each launch of the command for this directory?
Does `/Volumes/NYPF257402/Film/data/PreservationMasters/10-bit_DPX/myd_380086_v01_pm_DPX/myd_380086_v01_pm_0000000.dpx` exists? (trying to clarify of RAWcooked send a bad file name)
Is it the same behavior if you do `rawcooked --display-command --all /Volumes/NYPF257402/Film/data/PreservationMasters/10-bit_DPX/myd_380086_v01_pm_DPX ` then launch the displayed command?
Is it same bahavior if you copy the content on a local drive?

**Comment by bturkus** [comment]
thanks for all the ideas jerome! I tried the `--display-command` approach, and that seems to be working just fine. It's looking to me like something might be going awry when I build RAWcooked from source (I also continued testing with the most recent snapshot, and I don't seem to be encountering the problem there either). I still don't know what's really going on, and I know 
I didn't experience this issue in the past when building from source, but we do seem closer to figuring it out.

**Comment by JeromeMartinez** [comment]
You mean that you don't have this issue when you try our binaries, only when you try your builds?
Weird, we use the compiler of each distro for building our binaries, so it should be the same as the one you use, and we don't use any specific compiler flags.
The only difference between your sources and our sources is the license key related code, which has no impact on the scan of files.

**Comment by paulmer** [comment]
Hi everyone, I've been pursing a similar problem, and I wonder if this is the same thing:  It looks there's a bug in Source/Lib/FileIO.cpp in filemap::Close() that prevents file descriptors from being closed and causes the program to run out of descriptors on larger films.  This shows up when ffmpeg is called because the return value of FileMap.Open_ReadMode(*Name) in parse_info::ParseFile_Input (line 148) isn't checked (which would reveal that open eventually fails).  The main fix is to correct the test in filemap::Close() (~line 169) changing the test from "if (P == -1)" to "if (P != -1)", but the result code from Open_ReadMode needs to be tested as well (as probably should the result of the close() system call).  (Line numbers from today's sources in the master branch on GitHub.)

I'm curious why the choice was made to avoid C++ exceptions and use return codes everywhere?

**Comment by JeromeMartinez** [comment]
> changing the test from "if (P == -1)" to "if (P != -1)"

Thank you a lot for pointing out the source of the issue, nasty bug.

>  the return value of FileMap.Open_ReadMode(*Name) in parse_info::ParseFile_Input (line 148) isn't checked

And same, this should have been checked in order to catch early the I/O issue.

> (as probably should the result of the close() system call). 

Same!

Please test this [snapshots](https://mediaarea.net/download/snapshots/binary/rawcooked/20190529/), it contains code from https://github.com/MediaArea/RAWcooked/pull/225, and let me know if it resolves the main issue.

I'll review all the system calls in order to handle all system errors (and also implement the catch of SIGBUS when the file is no more accessible during reading or writing).

> I'm curious why the choice was made to avoid C++ exceptions and use return codes everywhere?

Me hiding... Mainly bad old habits from when C++ exceptions were very costly, optionally a try to get a small binary for fitting as much as possible in CPU cache (maybe [Premature Optimization](https://en.wikipedia.org/wiki/Program_optimization#When_to_optimize)).

**Comment by paulmer** [comment]
Terrific, thanks for the really quick response!  I tested the snapshot on two of our videos that had been failing and it works perfectly.

>> I'm curious why the choice was made to avoid C++ exceptions and use return codes everywhere?
> Me hiding... Mainly bad old habits from when C++ exceptions were very costly, optionally a try to get a small binary for fitting as much as possible in CPU cache (maybe Premature Optimization).

Ah, I understand now, thanks.  Having worked in Java recently, that level of optimization doesn't even fall on the radar.

**Comment by JeromeMartinez** [comment]
> thanks for the really quick response!

When most of the work (finding the source of the issue) is done, it makes things easier! ;-)
