### ISSUE TITLE
ditto key conformance

### ISSUE THREAD

**Issue by bturkus** [MediaArea/RAWcooked#223]
Hi Everyone,

We've been testing out new RAWcooked conformance checking features, and we seem to be getting a whole lotta "non-conforming ditto key" messages. This is kinda how Genevieve and feel right about now:

![2019-05-14](https://user-images.githubusercontent.com/8987230/57732432-0d67de80-766b-11e9-8dab-821a03e75a9b.jpg)

Perhaps this is less a RAWcooked issue, and more a question to the larger cooking community, but does anyone out there have any opinions—should we be overly concerned about this? SMPTE spec and FADGI recommendations are pretty opaque when it comes to ditto key, and "Inconsistent. Sometimes used correctly, sometimes blank" feels like license to not care too much. Thoughts?

Ben

**Comment by retokromer** [comment]
This would make a great panel discussion for NTTW4!

**Comment by JeromeMartinez** [comment]
> SMPTE spec and FADGI recommendations are pretty opaque when it comes to ditto key

In my opinion it is pretty clear:
`0 = same as previous frame; 1 = new. Indicates that all fields are the same as the previous frame in the sequence except for fields related to the frame number (48, 50, 58, 61)`

"0b11111111111111111111111111111111" (a.k.a. -1) is not in spec ;-), but it is classically used in other DPX fields for meaning "unknown" ("blank" in FADGI wording?), my suggestion is to consider -1 as acceptable (=no implementation error reported by RAWcooked).

**Comment by bturkus** [comment]
got it. thanks all. closing...

**Comment by JeromeMartinez** [comment]
Hum, Before definitely closing I would like to be sure that I the idea of ignoring -1 is OK.
