### ISSUE TITLE
Request for framemd5 option

### ISSUE THREAD

**Issue by digitensions** [MediaArea/RAWcooked#245]
Hi I’m just running through some workflows for exporting RAWcooked files to LTO and have decided to make framemd5 checksum manifests as part of long term storage sidecar files (and in line with vrecord capture and IFI copyit generated manifests).

I wonder if this could be an easy function to incorporate into the RAWcooking process?

Many thanks.

**Comment by kieranjol** [comment]
Just to clarify, copyit just uses whole file md5, not framemd5s.. we stopped using framemd5 with rawcooked due to whole file manifests being more useful due to rawcooked bring reversible.

**Comment by digitensions** [comment]
Oops, my mistake! Apologies

**Comment by digitensions** [comment]
Reversing my request, on the basis of RAWcooked being reversibly :)
