### ISSUE TITLE
[question] same value for SHA-1 and SHA-256?

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#26]
Is the value `0x21` correct at line 29
https://github.com/MediaArea/RAWcooked/blob/fb26f2ca10ed6c621dfdfefea1b549f1b7768119/Source/Lib/RAWcooked/RAWcooked.cpp#L28-L29? Should this not read e.g. `0x22`?

**Comment by JeromeMartinez** [comment]
Typo, will fix.
Note that this is not yet used (and code is currently ugly, will be changed)

**Comment by retokromer** [comment]
OK, no problem. Next time I will make a PR. I was just unsure if I was missing something «de très tordu».

**Comment by JeromeMartinez** [comment]
Could be based on element size (e.g. I change to SHA-2 so any length is possible, 256 or 512, not yet sure of the final version but no impact on RAWcooked initial format as it is not mandatory for reversability)

**Comment by retokromer** [comment]
Note that for archival purpose MD5 is very fine and there is scientifically no need for SHA-n. Yet IRL we have do deal with SHA-n as well. I will try to find an idea how to manage in our context those… and the future «broken» versions.

**Comment by JeromeMartinez** [comment]
SHA-1 or SHA-256 may be faster thanks to Intel SHA extension, but I don't know (yet) which one is faster. Anyway, for future implementation, will not be the first thing I'll implement.

**Comment by retokromer** [comment]
I haven’t tested Intel’s SHA extensions so far. I’ll do it… during the next weekend.
