### ISSUE TITLE
Documentation: Expectations / constraints on folder structures and filenames

### ISSUE THREAD

**Issue by stephenmcconnachie** [MediaArea/RAWcooked#261]
As I'm about to start implementing a RAWCooked workflow for our DPX sequences, I am aiming to write specifications for our folder structuring / DPX filenaming, to ensure we prepare our backlog media appropriately for RAWCooked, and to help us prepare appropriately for new scanning activity.

I checked the early Issues here to remind myself of the expectations / constraints, but I wonder if it would be useful to document those in the README, or elsewhere.

As I'm going to have to write them for internal use, I would offer myself as a drafter of such a thing, but I would need input from active users, to make sure I have undesrtoiod correctly, and fix my errors.

If this sounds useful, I can start a Google Doc and share the editable link here?

Stephen

**Comment by JeromeMartinez** [comment]
I think it could be useful.
On our side we started a doc at https://github.com/MediaArea/RAWcooked/blob/master/Doc/User_Manual.md, but as you see it is very small. It would be great if users expand it, IMO it is better that a user manual is written by users when possible, as they see more the issues.
If you prefer a standalone document about your specific practice, it would be great to add it as another file at https://github.com/MediaArea/RAWcooked/tree/master/Doc , so it will be delivered to all users.

**Comment by retokromer** [comment]
>I think it could be useful.

I second it.

**Comment by mcampos-quinn** [comment]
You guys are the best.

**Comment by stephenmcconnachie** [comment]
OK I added some stuff in https://github.com/MediaArea/RAWcooked/blob/master/Doc/User_Manual.md with a pull request. It may be too detailed, and it probably has misunderstandings too - please correct it!

**Comment by JeromeMartinez** [comment]
Closing the ticket as there was a corresponding PR, but don't hesitate to open new issues or PR if you have more ideas about documentation, the project is intended to be collaborative, especially on the doc.
