### ISSUE TITLE
[wish] make a new release

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#271]
The current release 18.10.1 is one year old, and many improvements have been made in the meantime.

**Comment by JeromeMartinez** [comment]
Right, I am late, I try to have a clean version ASAP.

**Comment by retokromer** [comment]
Could a new release be made by end of next week? Thank you!

**Comment by JeromeMartinez** [comment]
I am aware I am super late on this, but still reluctant to push a release with partial parts (there are some features which are implemented, but not completely).

**Comment by retokromer** [comment]
No problem, I’ll make an unofficial release for my class in Hyderabad.

**Comment by retokromer** [comment]
I just made an official release, needed for my FHF/FIAF class in Hyderabad, therefore closing.

**Comment by retokromer** [comment]
>The current release 18.10.1 is one year old, and many improvements have been made in the meantime.

The current release is now 20 months old and so much has been improved since then. In my opinion, a new release is really needed! Also because new developments seem to be stalled during the last weeks.

**Comment by JeromeMartinez** [comment]
Definitely super mega late and my todo-list is very long, I try to catch up this delay as soon as possible.
