### ISSUE TITLE
Supported file sizes?

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/RAWcooked#33]
Hi, I installed the latest 16.04 Ubuntu build.
I made a dpx sequence with
`ffmpeg -f lavfi -i testsrc=size=2048x1556 -pix_fmt rgb48le -t 1 /home/kieran110s/dpxo/out_%06d.dpx`

I get 'Untested DPX file size' when I try to encode with `-e`

```
$ rawcooked -e out_000001.dpx  
Untested DPX file size, please contact info@mediaarea.net if you want support of such file
$ rawcooked  /home/kieran110s/dpxo
Segmentation fault (core dumped)

```

What I'm starting to think is that currently, the app should be used without `-e`, and instead the ffmpeg command should be copy pasted into a terminal?

**Comment by retokromer** [comment]
The flags are not implemented yet.

**Comment by JeromeMartinez** [comment]
`rawcooked out_000001.dpx` or `rawcooked /home/kieran110s/dpxo/out_%06d.dpx` only for the moment, the commands you did are the one you could expect but the help part is in advance compared to what is implemented.

**Comment by retokromer** [comment]
@kieranjol FYI: The flags are currently planned to simplify embedding in other software (as a Bash script or a plug-in for Diamant) and to give the possibility to force when needed. The «normal» use will remain without passing flags and parameters.

**Comment by kieranjol** [comment]
Thanks both, this all makes sense.
