### ISSUE TITLE
[question] why `context=0`?

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#36]
Why is `context=0` chosen at https://github.com/MediaArea/RAWcooked/blob/master/Source/CLI/Main.cpp#L384? I would have set `context=1`, but I may be wrong.

**Comment by JeromeMartinez** [comment]
With some files I tested, `context=1` was actually less efficient (compression ratio), so by default I set `context=0`.
All FFV1 settings (slice_x, slice_y, coder, context, level...) will be modifiable (options).

**Comment by retokromer** [comment]
Thank you for the information! I will check if we have statistics on compression time and rate, because, if I am nor completely wrong, we usually choose `context=1`.
