### ISSUE TITLE
--output-version 2 warning

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/RAWcooked#361]
https://github.com/MediaArea/RAWcooked/pull/352

I've encountered some sequences that require this option, or I get that warning about attachments too big. I see that a warning appears saying that this is a preview release, and that this option should only be used when you know what you're doing.
I'm wondering about any risks involved in just leaving this option turned on all the time when automating workflows. From what I can see, you'll only know if this option is needed if the attachment gets too big, so it can be difficult to predict when it's required, so leaving it turned on permanently seems like it would make sense? Main issue is incompatibility with earlier rawcooked versions, but I don't see this being an issue?

**Comment by digitensions** [comment]
Hi Kieran, we use this option at present. This encoding command is only activated in the scripts when a regular encoding fails with messages 'Error: undecodable file is becoming too big.' or 'Error: the reversibility file is becoming big.'

I understand there are plans to merge this feature into the --all command at some point, defer to @JeromeMartinez regarding this though.  Obviously, if that happens we won't require this check or use of the --output-version 2 command.  We still get a lot of non-zero padding making large reversibility data files so need it in any future releases if not merged into --all.

Cheers!

**Comment by kieranjol** [comment]
Thanks Joanna! Does adding it as an attachment after extend the rawcooking time by much? I hadn’t factored this in at all. 
I’d considered taking your approach with only triggering the option if it failed with those errors, but the error might occur many hours into the encode, and I’m not using watchfolders, just seq2ffv1, so I was considering just leaving it on all the time instead…

**Comment by digitensions** [comment]
I don't know if it extends time to be honest Kieran. This isn't something I have measured, as my time is elsewhere at the moment.  I assumed it must, but it could be next to nothing.  Definitely something to ask @JeromeMartinez I think. If not, then like you we could just leave this flag on in retrospect.

I have to split some DPX sequences soon for some '--check' tests I want to run, so I can see if it adds anything to encoding time then!

**Comment by kieranjol** [comment]
Ah awesome, we can compare notes. I’ve not done much testing on it so I can
report back as well once I get around to it. Thanks for all this! My main
worry was just that adding this flag for everything was dangerous in some
unknown way.

**Comment by JeromeMartinez** [comment]
> I'm wondering about any risks involved in just leaving this option turned on all the time when automating workflows.

@digitensions and another customer are using it for a while, I expect that this is stable now. But "all the time" means that an old version of RAWcooked will not be able to revert to DPX, if fine for you, well use the option all the time.

We still plan to do an automatic move from v1 to v2 so no need to start again the analysis, but not yet done.

> That said, I understand there are plans to merge this feature into the --all command at some point,

I don't know yet, I think that the automatic change will be enough for some time, the time that all users switch to a version of RAWcooked supporting the format v2.

> Thanks Joanna! Does adding it as an attachment after encoding extend the rawcooking time by much?

format v1 and v2 have the same time, it is just a matter about where is the reversibility content.

> My main worry was just that adding this flag for everything was dangerous in some unknown way.

In theory there is no regression, in theory... :), use ` --check` for being sure!
The only issue I see is the compatibility with older versions of RAWcooked.

**Comment by digitensions** [comment]
Brilliant, thank you for confirming Jérôme, and yes happy to compare notes Kieran!

**Comment by kieranjol** [comment]
I don’t see any issue with an older rawcooked not being able to work, thanks both for clarifying this! @hyz2993 we should be able to safely add this to seq2ffv1 it seems!
