### ISSUE TITLE
Error: undecodable DPX version number of header format

### ISSUE THREAD

**Issue by megan-mcshea** [MediaArea/RAWcooked#394]
I'm getting this error with a batch of vendor-produced DPX sequences:

undecodable DPX version number of header format

There are non-zero padding characters in the "Version Number of Header Format" field ("V1.0i" or other stray characters after the 1.0).

Is there any workaround that would allow me to encode the DPX with this error? or would you recommend I correct the files, or have the vendor correct the files?

Thanks.

**Comment by JeromeMartinez** [comment]
The spec is not very precise, even for V2, we are a bit too strict about that, we'll relax the check and permit such kind of file soon.

Spec:
"ASCII vers[8];          /* which header format version is being used (v1.0)*/"
so not so much hint about what is acceptable or not.

> or would you recommend I correct the files,

As the spec is not precise, I think that it would not worth it to "fix" that if no other tool fails to read such file, we just change the validation rules on our side.

**Comment by megan-mcshea** [comment]
Hello, Checking in about this issue. We'll need to proceed with these files in the next few months. Do you think you might get to the issue in that time frame? Or should we correct the header so that it doesn't throw the error as-is? 
Thanks :)

**Comment by JeromeMartinez** [comment]
Apologizes for the huge delay, it will be in your time frame for sure, and I try to do it before and of month.

**Comment by megan-mcshea** [comment]
No apologies necessary. Thanks, Jerome!

**Comment by JeromeMartinez** [comment]
@megan-mcshea you can test with [latest development snapshots](https://mediaarea.net/download/snapshots/binary/rawcooked/).
