### ISSUE TITLE
What data would be (potentially) missing?

### ISSUE THREAD

**Issue by dlasusa** [MediaArea/RAWcooked#402]
If I were to:

1. Get checksums of DPX files and store them.
2. Convert DPX files to an MKV using RAWcooked for the encode (no padding, coherency, conformance checks)
3. Convert MKV back to DPX using RAWcooked for the decode (no checks)
4. Get checksums of the new DPX files
5. Compare original checksums vs. new checksums

Assuming the checksums all came back as identical...what might I still be missing by skipping the other checks in RAWcooked?

Thanks!

**Comment by JeromeMartinez** [comment]
You do checks that RAWcooked does, so at the end it is same :).

**Comment by dlasusa** [comment]
Gotcha.  Thanks!
