### ISSUE TITLE
[wish] add the version to the help message

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#42]

**Comment by retokromer** [comment]
If possible, please add this in the first beta release, because it simplified the communication between users and developers.

**Comment by JeromeMartinez** [comment]
when I do e.g. "ls --help", version is not there.
I added " --version" option in https://github.com/MediaArea/RAWcooked/pull/63.

**Comment by retokromer** [comment]
Hmm… That’s just one example. When I call e.g. `bash --help`, I got:

<img width="904" alt="bildschirmfoto 2018-05-21 um 07 43 58" src="https://user-images.githubusercontent.com/3246607/40292317-e0497662-5cca-11e8-8032-4e2972f54b6e.png">

In fact, I was thinking about something like:

<img width="904" alt="bildschirmfoto 2018-05-21 um 07 37 57" src="https://user-images.githubusercontent.com/3246607/40292322-ee21f976-5cca-11e8-9559-e65edfe135ff.png">

or:

<img width="906" alt="bildschirmfoto 2018-05-21 um 07 38 14" src="https://user-images.githubusercontent.com/3246607/40292329-fb741d70-5cca-11e8-951a-0022758ab671.png">

but I am fine with the solution you implemented.
