### ISSUE TITLE
sh: ffmpeg: command not found

### ISSUE THREAD

**Issue by Lawrence58** [MediaArea/RAWcooked#430]
Hello
I opened the issue Segmentation Fault 11 on One of Two Macs #429 below.  Now, contrary to what I said on it, suddenly rawcooked stopped working on my iMac Pro too.  I have no idea why. 

```
rawcooked --check  

Track 1:                                                    
  27292_ChA_RAW_%08d.dpx
 (00086400 --> 00093398)
  DPX/Raw/RGB/10bit/U/BE/FilledA

sh: ffmpeg: command not found
```

ffmpeg version N-110544-g57f264e78c-tessus is fully operational.

rawcooked v23.09
iMac Pro - Mojave v10.14.6

Any suggestions will be appreciated.

**Comment by JeromeMartinez** [comment]
We rely on the installed ffmpeg, it must be reacheable on your system. try `ffmpeg` with your command line, if the behavior is "command not found", you need to install ffmpeg (with homebrew, a binary from FFmpeg website, or [our own build](https://mediaarea.net/download/snapshots/binary/ffmpeg/latest/FFmpeg_Bin_Latest_Mac_Static_x64.zip)).

If you don't want that FFmpeg is reachable everywhere, you can specify a path for reaching ffmpeg with ` -b /path/to/ffmpeg`.

**Comment by retokromer** [comment]
(Only in case @JeromeMartinez answer should not fix the issue: Did you update Homebrew? It has been messing up a few macOS-related things lately.)

**Comment by Lawrence58** [comment]
I reinstalled FFMPEG and rawcooked and updated Homebrew and other terminal-related apps.  That fixed the problem on the iMac Pro.
