### ISSUE TITLE
Warning: non-conforming DPX total image file size

### ISSUE THREAD

**Issue by Lawrence58** [MediaArea/RAWcooked#434]
I am trying to troubleshoot something.  I have a set of DPX sequences from a film scanning vendor.  When I rawcooked them I get a warning.  This is what it looks like for one of the sequences.  The hex value changes with each sequence.
`Warning: non-conforming DPX total image file size (x17373).  At least 1 file is not conform to specifications.`

Is the hex number the file size of the offending file or something else?  I have checked the file size of some of the DPX files in the sequence referenced above but none of them are close to that.  Can you explain this situation to me please?
Thx.

**Comment by Lawrence58** [comment]
Thanks.  That explains it.  And, the number of occurrences 17373 matches the number of files in the sequence.

**Comment by JeromeMartinez** [comment]
So the DPX file is not conforming to the specs, and RAWcooked does its job by warning you about that.
Depending on other file characteristic, it may be just the tool which is buggy by "forgetting" 4 KiB or maybe there is an extra (non conforming) content after the file not part of the DPX content.

You can disable the conformance checker if you prefer, with ` --no-conch`.
