### ISSUE TITLE
add --log option

### ISSUE THREAD

**Issue by dericed** [MediaArea/RAWcooked#441]
I suggest standardized the rawcooked log to include a few more details. Currently in `rawcooked -h` it suggests

```
EXAMPLE: Custom encoding with export of console messages to log file
       rawcooked --check --coherency --conch --hash --encode -framerate 24
       /path_to_av_raw_data/ >> RAWcooked_encoding.log If you want to retain
       the console output of the RAWcooked encoding or decoding processes, you
       can set the stdout to a separate log file. This option is useful if
       you're automating batch encodings and need to assess the log outputs to
       make decisions within the logic of your code.
```

When I try this, I get the following in the log
```

Info: Reversibility data created by RAWcooked 23.12.
Info: Uncompressed file hashes (used by reversibility check) present.

Reversibility was checked, no issue detected.
```

which is helpful to summarize the output but there's no reference to the source or the output or the options. Also with this approach some pertinent data isn't visible in the console output.

I suggest having a `--log file` option or perhaps use a flag `--log` which presumes the same name as the output with a `_rawcooked.log` extension. If the latter option, then perhaps `--all` could include that flag to log the output.

I suggest the log output include the following:
- rawcooked version
- ffmpeg version
- full command used
- errors and warnings
- summary of the result

**Comment by JeromeMartinez** [comment]
Mockup:

```
RAWcooked 23.09, FFmpeg 4.4.2-0ubuntu0.22.04.1
./rawcooked --all relative/path/to/package

Track 1:
 video/%07d.dpx
 (0086945 --> 0086956)
 DPX/Raw/RGB/16bit/U/BE
Track 2:
 audio/fr.wav
 WAV/PCM/48kHz/24bit/6ch/S/LE
Extra files:
 md5deep.md5

Warning: non-conforming DPX ditto key.
At least 1 file is not conform to specifications.

Input size is x bytes, output size is y bytes (-z %).

Info: Reversibility data created by RAWcooked 23.09.
Info: Uncompressed file hashes (used by reversibility check) present.

Reversibility was checked, no issue detected.
```

Note: I prefer to use relative path to package rather than the full path (I tweak a bit there the exact command line) for not keeping forever a temporary location, i.e. I show the relative path stored in the reversibility data

**Comment by JeromeMartinez** [comment]
> If the latter option, then perhaps `--all` could include that flag to log the output.

I consider `--all` to be used for the settings of the output file, not the extra options for logging.
I am currently thinking to `--log XXX`  and `--log-auto` (the latter would created a `output.mkv.rawcooked.log` file).

**Comment by retokromer** [comment]
>Note: I prefer to use relative path to package rather than the full path (I tweak a bit there the exact command line) for not keeping forever a temporary location, i.e. I show the relative path stored in the reversibility data

+1

**Comment by retokromer** [comment]
>I consider `--all` to be used for the settings of the output file, not the extra options for logging.

+1
