### ISSUE TITLE
"All about editing your MOV files"

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#61]
I presume that the description on https://github.com/MediaArea/RAWcooked/blob/236cdf136c0690ba398ed2347104cf707bd2a017/Source/Install/RAWcooked_GUI_Windows_x64.nsi#L51 and https://github.com/MediaArea/RAWcooked/blob/236cdf136c0690ba398ed2347104cf707bd2a017/Source/Install/RAWcooked_GUI_Windows_x64.nsi#L55 come from a copy-and-paste.

**Comment by JeromeMartinez** [comment]
Resolved with https://github.com/MediaArea/RAWcooked/pull/65.
(description could be changed before release if this is not the best choice)
