### ISSUE TITLE
[wish] add a Homebrew/Linuxbrew formula

### ISSUE THREAD

**Issue by retokromer** [MediaArea/RAWcooked#9]

**Comment by JeromeMartinez** [comment]
When we have a beta release.

**Comment by retokromer** [comment]
Any news? (I’m flying tomorrow to Praha were the first release should be presented.)

**Comment by JeromeMartinez** [comment]
We are definitely late for the 1.0 release. Will present excuses (and i am the only one to blame) face to face.

When correctly used (listing all attachments manually), it is pretty stable. Will merge the PR with support of a directory tomorrow.

So we could do an alpha release with current snapshot in our homebrew, knowing it is still to be extensively tested.

**Comment by retokromer** [comment]
Thank you very much for the news! It’s not of my interest at all to blame others. I’ll just be in Prague from tomorrow noon until Thursday noon, and I will have many business meetings (also seven regarding precisely the possible adoption of RAWcooked in FIAF archives).

**Comment by JeromeMartinez** [comment]
Snapshots are in https://github.com/MediaArea/homebrew-mediaarea now.
Will update when something of interest is merged.

**Comment by retokromer** [comment]
Thank you!
